import fs from 'fs';
const html=fs.readFileSync(process.env.D+'/scheduler.html','utf8');
const shared=fs.readFileSync(process.env.D+'/shared.js','utf8'); const scripts=[shared,...[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]).filter(b=>!/document\.write/.test(b))];
function mk(tag){ return { tag, dataset:{}, querySelector(){return null;}, querySelectorAll(){return [];}, scrollTop:0, className:'', textContent:'', children:[], style:{}, value:'', hidden:false, parentNode:null, classList:{add(){},contains(){return false;}}, appendChild(c){c.parentNode=this;this.children.push(c);return c;}, removeChild(c){this.children=this.children.filter(x=>x!==c);}, setAttribute(){}, set innerHTML(v){this.children=[];}, get innerHTML(){return '';} }; }
const reg={}; const body=mk('body'); global.document={ body, createElement:mk, createTextNode:t=>({tag:'#text',textContent:String(t),children:[]}), querySelector:s=>s==='.veil'?null:(reg[s]||(reg[s]=mk('div'))) };
const lists=[{id:'l1',name:'Workshop Jobs - Not Started'},{id:'l2',name:'Removals / Recycling / Skips / Stock / Plastic'},{id:'l3',name:'Holidays / Leave'}];
const cards=[{id:'c1',name:'Skipton - C4B36B - Harrison Drury',idList:'l1',due:'2026-09-15T12:00:00.000Z',start:null,labels:[{name:'Delivery/Installation'}],members:[{fullName:'Bart H'}],desc:'x',customFieldItems:[]},
             {id:'c2',name:'Blackpool - 5FAEDC - James Knowles',idList:'l2',due:'2026-09-14T12:00:00.000Z',labels:[{name:'Removal Job'}],members:[],desc:'**Clearance Details**\n\n**Job**\nRef: **5FAEDC**\n\n**Site Contact**\nMichael Knowles \u2014 **07946508174**\n\n**Collection Address**\n**20 Dickson Road, Blackpool, FY1 2AE**\n\n**Items to Clear**\n{"metal\\_filing\\_cabinets":5}\n\n**Sign-off link:** [Open the sign-off form](https://x.y/z)'},
             {id:'c4',name:'Bath - 1476F6 - Elite Office Furniture - 111321',idList:'l2',due:'2026-09-16T07:00:00.000Z',labels:[{name:'Clearance - Sub-contractor'}],members:[],desc:'**Clearance Details**\n\nRef: **1476F6**\n\n**Items to Clear**\n194 x Swivel chairs\n\n**Parts**\nProduction: no\nSite: no\nTransport: Example Haulage, customer loads\nLabour: unload at Forton',customFieldItems:[]},
             {id:'c5',name:'Property Compass - F48E55',idList:'l2',due:'2026-09-16T07:00:00.000Z',labels:[{name:'Resale - Customer Collects'}],members:[],desc:'**Parts**\nProduction: yes\nSite: no\nTransport: customer collects\nLabour: no',customFieldItems:[]},
             {id:'c6',name:'West Midlands - 98ACFE - Example Interiors - Estimate: 111270',idList:'l1',due:'2026-09-30T07:00:00.000Z',labels:[{name:'Refurb - Collect & Return'}],members:[],desc:'**Refurb Collection Details**\n\nRef: **98ACFE**\n\n**Subcontract Work and Materials**\nSeat pads: Deliver to Example Upholstery (LA1 1AA) on 2026-09-17\nSeat pads: Collect from Example Upholstery (LA1 1AA) on 2026-09-26 by courier\n\n**Loan chairs**\n**30 loan chairs** out with the collection, back on the return:\n\u00b7 30 x Bene Filo Mesh Meeting Chair | Black',customFieldItems:[]},
             {id:'c3',name:'Rob (Annual Leave)',idList:'l3',due:'2026-09-18T12:00:00.000Z',labels:[],members:[]}];
global.window={__TODAY:'2026-09-14T12:00',TrelloPowerUp:{iframe(){return { lists:()=>Promise.resolve(lists), cards:()=>Promise.resolve(cards), board:()=>Promise.resolve({name:'Jobs - Planning Board',members:[]}), get:(a,b,c,d)=>Promise.resolve(d), set:()=>Promise.resolve() };}}};
global.TrelloPowerUp=global.window.TrelloPowerUp;
try{ new Function(scripts.join('\n'))(); }catch(e){ console.log('SYNC THROW',e.stack.split('\n').slice(0,3).join('\n')); }
setTimeout(()=>{ console.log('src:',reg['#src'].textContent); console.log('title:',reg['#title'].textContent); },200);
process.on('unhandledRejection',e=>console.log('REJECT',e.stack.split('\n').slice(0,4).join('\n')));
setTimeout(()=>{ const walk=(n,o=[])=>{o.push(n);(n.children||[]).forEach(c=>walk(c,o));return o;}; const T=walk(reg['#board']).map(x=>x.textContent).filter(Boolean).join(' '); console.log('board has Skipton:',/Skipton/.test(T),'Knowles:',/Knowles/.test(T),'Rob leave:',/Rob on leave/.test(T)); },300);

setTimeout(()=>{ const c=[...(function walk(n,o=[]){o.push(n);(n.children||[]).forEach(x=>walk(x,o));return o;})(reg['#board'])].find(n=>n.className==='card'&&/Knowles/.test((function T(n){return (function walk(n,o=[]){o.push(n);(n.children||[]).forEach(x=>walk(x,o));return o;})(n).map(x=>x.textContent).join(' ');})(n))); c.onclick();
  const v=body.children.find(n=>n.className==='veil'); const T=(function walk(n,o=[]){o.push(n);(n.children||[]).forEach(x=>walk(x,o));return o;})(v).map(x=>x.textContent).filter(Boolean).join(' ');
  console.log('clean contact:',/Contact Michael Knowles,\s+07946508174/.test(T),'| items:',/Items \(1\) 5 x Metal filing cabinets/.test(T),'| no ** left:',!/\*\*|\\_|Sign-off/.test(T)); },400);
setTimeout(()=>{ const walk=(n,o=[])=>{o.push(n);(n.children||[]).forEach(c=>walk(c,o));return o;}; const T=walk(reg['#board']).map(x=>x.textContent).filter(Boolean).join(' '); console.log('production due shown:',/Skipton - Harrison Drury .*(Production due Fri 11 Sep|Production not scheduled)/.test(T)); },500);

// JOB SHEETS: a fake jsPDF records every line of text; the sheet for the day must name the operative, the job and the hand-back block.
setTimeout(()=>{ const out=[]; class FakeDoc{ constructor(){ this.internal={pageSize:{}}; } setFont(){} setFontSize(){} setTextColor(){} setFillColor(){} setDrawColor(){} setLineWidth(){} roundedRect(){} rect(){} line(){} addPage(){} setPage(){} getNumberOfPages(){return 1;} splitTextToSize(t){return String(t).split('\n');} text(t){ out.push(Array.isArray(t)?t.join(' '):String(t)); } save(n){ out.push('SAVED '+n); } }
  global.window.jspdf={jsPDF:FakeDoc}; global.alert=m=>out.push('ALERT '+m);
  try{ global.window.__crewSheetsPdf('2026-09-15'); }catch(e){ console.log('SHEETS THROW',e.stack.split('\n').slice(0,3).join('\n')); }
  const T=out.join(' | '); console.log('recycling tally on the sheet:',/RECYCLING/.test(T)&&/TARGET UNITS/.test(T)&&/Units processed today:/.test(T)&&/Plastic shredding today/.test(T)&&/PA66/.test(T)&&/Tools put back/.test(T)); console.log('job sheets:',/Bart, Tue 15 Sep/.test(T)&&/Skipton - Harrison Drury/.test(T)&&/no time set/.test(T)&&/END OF DAY/.test(T)&&/SAVED job-sheets-2026-09-15\.pdf/.test(T));
},700);

// THE PARTS: a sub-contractor clearance with a labour unload becomes a contractor job plus a labour leg on the due day.
setTimeout(()=>{ const all=global.window.__allJobs(); const main=all.find(j=>j.id==='c4'), leg=all.find(j=>j.isLeg&&j.leg.type==='labour'&&j.leg.parent==='c4');
  const cc=all.find(j=>j.isLeg&&j.leg.type==='labour'&&j.leg.parent==='c5'); const dl=all.find(j=>j.isLeg&&j.leg.parent==='c6'&&j.leg.type==='to_sub'), cl=all.find(j=>j.isLeg&&j.leg.parent==='c6'&&j.leg.type==='labour'); console.log('legs named:', !!dl&&/^Deliver to Example Upholstery \(LA1 1AA\), Seat pads, for Example Interiors/.test(dl.title)&&dl.date==='2026-09-17'&&dl.site&&!!cl&&/unload in from Example Upholstery/.test(cl.leg.where)&&cl.date==='2026-09-26'); console.log('job parts:', !!main&&main.contractor==='Example Haulage'&&!!leg&&leg.date==='2026-09-16'&&!leg.site&&leg.movement==='Labour unload'&&!cc);
},800);

setTimeout(()=>{ const rt=new Function(shared+';return recTarget;')(); console.log('rec target:', rt(465)===100 && rt(0)===0 && rt(180)===39); },850);
setTimeout(()=>{ const li=new Function(shared+';return loanItemsOf;')(); const got=li(cards.find(c=>c.id==='c6').desc); const it=new Function(shared+';return itemsOf;')()(cards.find(c=>c.id==='c6').desc,[]); console.log('loan chairs in the van, not the items:', got.length===1 && /^30 x Bene/.test(got[0]) && !it.some(l=>/Bene/.test(l))); },900);
